version = 1

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "scala"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "go"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "python"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"

test_patterns = ["**/src/test/**"]
